name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Log in to Docker Hub
       # uses: docker/login-action@v2
        #with:
         # username: ${{ secrets.DOCKER_USERNAME }}
          #password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t time-api:latest ./app
          docker tag time-api:latest obike007/time-api:latest

      - name: Push Docker image to Docker Hub
        run: |
          docker push obike007/time-api:latest

  deploy-infrastructure:
    name: Deploy Infrastructure with Terraform
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform
        run: terraform validate
        working-directory: ./terraform

      - name: Plan Terraform
        run: terraform plan -var="assign-time-api=obike007/time-api:latest"
        working-directory: ./terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="assign-time-api=obike007/time-api:latest"
        working-directory: ./terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

